"""metal rates + making charges + variant purity

Revision ID: 74770827d103
Revises: f65fb39eca4f
Create Date: 2026-07-22 13:18:06.834800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74770827d103'
down_revision: Union[str, None] = 'f65fb39eca4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metal_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material', sa.String(length=20), nullable=False),
    sa.Column('purity', sa.String(length=20), nullable=False),
    sa.Column('rate_per_gram', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material', 'purity', name='uq_metal_rate_material_purity')
    )
    op.add_column('product_variants', sa.Column('purity', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('making_charge_type', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('making_charge_value', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'making_charge_value')
    op.drop_column('products', 'making_charge_type')
    op.drop_column('product_variants', 'purity')
    op.drop_table('metal_rates')
    # ### end Alembic commands ###
